# Generated by Django 5.0.6 on 2024-06-25 17:50

import django.db.models.deletion
import erd.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diseases',
            fields=[
                ('DiseasesID', models.AutoField(primary_key=True, serialize=False)),
                ('Deasesname', models.CharField(max_length=100)),
                ('DeasesDiscription', models.CharField(max_length=100)),
                ('commen_symptoms', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['Deasesname'],
            },
        ),
        migrations.CreateModel(
            name='Escort',
            fields=[
                ('FirstName', models.CharField(max_length=100)),
                ('LasttName', models.CharField(max_length=100)),
                ('EscortID', models.AutoField(primary_key=True, serialize=False)),
                ('Email', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('PhoneNumber', models.CharField(max_length=14)),
                ('yourHandel', models.CharField(max_length=100)),
                ('ProfilePicture', models.ImageField(upload_to='photos%y%m%d')),
                ('Male', models.BooleanField(default=True)),
                ('Female', models.BooleanField(default=False)),
                ('LastModified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['yourHandel'],
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('DrugName', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('purpose_of_use', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=100)),
                ('Duration_of_use', models.DateTimeField()),
                ('number_of_times_day', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
                ('expire_date', models.DateField(blank=True)),
                ('Pillsnum', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['DrugName'],
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('emaill', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=100)),
                ('RePassword', models.CharField(max_length=100)),
                ('PhoneNumber', models.CharField(max_length=14)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='patient',
            fields=[
                ('FirstName', models.CharField(max_length=100)),
                ('LasttName', models.CharField(max_length=100)),
                ('patientID', models.AutoField(primary_key=True, serialize=False)),
                ('Email', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('PhoneNumber', models.CharField(max_length=100)),
                ('Handel', models.CharField(max_length=100)),
                ('ProfilePicture', models.ImageField(upload_to='photos%y%m%d')),
                ('Male', models.BooleanField(default=True)),
                ('Female', models.BooleanField(default=False)),
                ('DiseaseID', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='erd.diseases')),
                ('EscortID', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='erd.escort')),
            ],
            options={
                'ordering': ['Handel'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('DrugName', models.CharField(max_length=50)),
                ('prescriptionID', models.AutoField(primary_key=True, serialize=False)),
                ('exrays_test', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('DiseasesID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='erd.diseases')),
                ('EscortID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='erd.escort')),
                ('patientID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='erd.patient')),
            ],
            options={
                'ordering': ['patientID'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to=erd.models.GenerateProfileImagePath())),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('ReminderID', models.AutoField(primary_key=True, serialize=False)),
                ('StartDate', models.DateTimeField()),
                ('EndDate', models.DateTimeField()),
                ('State', models.BooleanField(default=False)),
                ('AlarmRecordes', models.TimeField()),
                ('Audio', models.FileField(default='default_audio.mp3', upload_to='audio/')),
                ('Notes', models.TextField(max_length=50)),
                ('Checked', models.BooleanField(default=False)),
                ('DrugName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders_as_drugname', to='erd.medicine')),
                ('patientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erd.patient')),
            ],
            options={
                'ordering': ['ReminderID'],
            },
        ),
    ]
